# https://taskfile.dev

version: '3'

tasks:

  build:
    cmds:
      - go build -o bin/weather-api cmd/main.go

  run:local:
    cmds:
      - ENV=local go run cmd/main.go

  docker:build:
    cmds:
      - docker build -t weather-api .