# https://taskfile.dev

version: '3'

tasks:

  build:
    cmds:
      - go build -o bin/weather-api cmd/main.go

  run:local:
    cmds:
      - ENV=local go run cmd/main.go

  docker:build:
    cmds:
      - docker build -t weather-api .

  generate:
    cmds:
      - go tool oapi-codegen -package v1 -generate "chi-server" -o internal/ports/http/v1/opeanpi_v1_server.gen.go api/v1/weather.yaml
      - go tool oapi-codegen -package v1 -generate "types" -o internal/ports/http/v1/opeanpi_v1_types.gen.go api/v1/weather.yaml
